
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Dec 04 12:39:50 EST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRLIT = 5;
  public static final int rw_BOOL = 27;
  public static final int LBRACKET = 15;
  public static final int MULT = 25;
  public static final int rw_IF = 26;
  public static final int SLASH = 37;
  public static final int rw_FALSE = 30;
  public static final int LPAREN = 7;
  public static final int SEMI = 6;
  public static final int rw_PRINT = 29;
  public static final int rw_TRUE = 31;
  public static final int MINUS = 24;
  public static final int RPAREN = 19;
  public static final int NOT = 42;
  public static final int INTLIT = 3;
  public static final int LT = 8;
  public static final int rw_CONST = 34;
  public static final int COMMA = 13;
  public static final int rw_ELSE = 41;
  public static final int GEQ = 18;
  public static final int rw_FUNC = 39;
  public static final int PLUS = 23;
  public static final int rw_READ = 40;
  public static final int rw_INT = 28;
  public static final int EOF = 0;
  public static final int rw_FOR = 32;
  public static final int RBRACKET = 14;
  public static final int error = 1;
  public static final int rw_PACKAGE = 35;
  public static final int COR = 22;
  public static final int rw_RETURN = 38;
  public static final int EQ = 16;
  public static final int ASG = 9;
  public static final int CHARLIT = 4;
  public static final int LBRACE = 10;
  public static final int rw_CHAR = 36;
  public static final int RBRACE = 11;
  public static final int CAND = 21;
  public static final int LEQ = 17;
  public static final int GT = 20;
  public static final int VAR = 33;
  public static final int NOTEQ = 12;
  public static final int IDENTIFIER = 2;
}

